spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  profiles: stg
  data:
    mongodb:
      host: localhost1
      port: 27017
      database: stg
---
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost2
      port: 27017
      database: prod
